### ISSUE TITLE
Using exec_command crashes steampipe in some cases

### ISSUE THREAD

**Issue by keenan-v1** [turbot/steampipe-plugin-exec#12]
**Describe the bug**
I am trying to use the exec_command plugin to run a `dig +short` against load balancer domain names to build a list of IP addresses in Postgres. When I try this query, it crashes. I'm not sure if it's the plugin crashing, or steampipe itself, but it doesn't crash with other plugins, hence starting here.

**Steampipe version (`steampipe -v`)**
v0.20.11

**Plugin version (`steampipe plugin list`)**
v0.0.3

**To reproduce**
Run this query:
```sql
select
    lb.dns_name,
    (select output from exec_command where command = 'dig +short ' || lb.dns_name) as ip_addresses
from
   aws_ec2_classic_load_balancer as lb
```
I understand this query may not be perfect, but I can't iterate on it as it crashes.

**Expected behavior**
I expect the query to return the load balancer DNS names along with the output from the `dig` command.

**Additional context**
I've attached the relevant log with the error.
[database-2023-09-11.log](https://github.com/turbot/steampipe-plugin-exec/files/12580937/database-2023-09-11.log)

**Comment by cbruno10** [comment]
Hey @keenan-v1 , sorry you're running into some issues!

If you just run `select output from exec_command where command = 'dig +short '` on the same server, does it return the correct results or does it crash?

Can you please look through your `~/.steampipe/logs/plugin-<date>.log` file as well and see if you notice any errors/warnings/crashes in there too?

Can you please also share your `~/.steampipe/config/exec.spc` file (with any sensitive info removed) include some details as to what type of machine the Exec plugin connection is configured to run on, e.g., local Linux RHEL laptop, EC2 Amazon Linux 2023, local Mac OS laptop, etc.?

Thanks!

Ify

**Comment by keenan-v1** [comment]
Hey! No worries!

I was able to reproduce the issue without using the AWS plugin:
```postgresql
with sample_data(dns_name) as (
    values ('google.com'), ('github.com'), ('yahoo.com')
)
select
    sd.dns_name,
    (select output from exec_command where command = 'dig +short ' || sd.dns_name) as ip_addresses
from sample_data as sd;
```
I also changed `dig +short` to a simple `echo`, but it still crashes.

Interestingly enough, this query here also crashes it.
```postgresql
with sample_data(dns_name) as (
    values ('google.com'), ('github.com'), ('yahoo.com')
)
select
    output
from sample_data as sd
cross join exec_command
where command = 'dig +short ' || sd.dns_name;
```
But this query does not:

```postgresql
with recursive test_data(n) as (
    values (1)
    union all
        select n+1 from test_data where n < 5
)
select
    (select output from exec_command where command = 'dig +short test' || n || '.com') as cmd_output
from test_data as t;
```

As for your questions:

> If you just run select output from exec_command where command = 'dig +short ' on the same server, does it return the correct results or does it crash?

It does not crash in this simple case.

> Can you please look through your ~/.steampipe/logs/plugin-<date>.log file as well and see if you notice any errors/warnings/crashes in there too?

I don't even see a plugin log for today, after crashing it a few times.

> Can you please also share your ~/.steampipe/config/exec.spc file (with any sensitive info removed) include some details as to what type of machine the Exec plugin connection is configured to run on, e.g., local Linux RHEL laptop, EC2 Amazon Linux 2023, local Mac OS laptop, etc.?

Here is my `exec.spc` (renamed with a .txt for GitHub). I made no changes.
[exec.spc.txt](https://github.com/turbot/steampipe-plugin-exec/files/12599369/exec.spc.txt)

I am running this locally on my MacBook Pro. I've included a screenshot of my About.

<img width="257" alt="Screenshot_9_13_23__11_29_AM" src="https://github.com/turbot/steampipe-plugin-exec/assets/2093265/e49d3b4f-94cf-449a-bfeb-7869bcc69bec">

I installed Steampipe via `brew`, if that helps.
