### ISSUE TITLE
remote-linux-connection-through-ssh fail and defaulted to connect as root instead of ec2-user

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-exec#6]
**Describe the bug**

https://hub.steampipe.io/plugins/turbot/exec#remote-linux-connection-through-ssh 

**This is my config setting in .spc**
```
connection "exec_remote_linux" {
  plugin = "exec"
  host = "ec2-13-233-111-222.ap-south-1.compute.amazonaws.com"
  user = "ec2-user"
  private_key = "/Users/xyz/rvvv/priv-key/docker-cis.pem"
}
```

Even though I provide the user as ec2-user, every time it tries to connect as root
```
> select output from exec_remote_linux.exec_command where command = 'ls -al'
Error: timeout - last error: SSH authentication failed (root@ec2-13-233-111-222.ap-south-1.compute.amazonaws.com:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by luisffc** [comment]
@rajlearner17 the config file is missing the protocol. It's required, but an issue on config processor is not making this argument mandatory. I'm currently working on a fix, but in the meantime you can safely use the plugin with the `protocol` set

**Comment by rajlearner17** [comment]
@luisffc Sounds good; I will give it a try today. Thanks

**Comment by cbruno10** [comment]
Closed in https://github.com/turbot/steampipe-plugin-exec/commit/324e3f89a0ed38f0f320d2a0d9f985f097aadcd7
